### PR TITLE
Added provision to store regulated profession and certificate number

### PR DESCRIPTION
**Pull request by Edzelopez**

### CODE REVIEW

**Comment by seamuslee001** [comment]
@Edzelopez so would we be right in that we need to clear this field as well when we 'archive' a credential as well? Also i'm presuming there is nothing in the front end form that allows the person to pick which credential is for a staff member correct

**Comment by Edzelopez** [comment]
Yes, archiving should be done as well. I will add that in. 
Correct, there is nothing on the front end to indicate which staff member has the proper credential. It is determined by the certificate number. There is a case where the certificate can either be a BCBA-D, even though we are saving the field as BCBA, but AO will adjust that manually as they approve listings.

**Review by seamuslee001 — APPROVED** [review]
These Changes work correct tested out by submitting a test registration and it correctly populated the staff member field with the correct information. Only need to handle the archiving but this code works as expected

**Review by seamuslee001 — APPROVED** [review]
Archive changes look good this is good to merge @Edzelopez

**Pull request merged**
