### PR TITLE
[WIP] AOSL-38: QA fixes for service application form

### PR DESCRIPTION
**Pull request by monishdeb**

### CODE REVIEW

**Comment by Edzelopez** [comment]
Hmm, I can see issues with this. By website, I meant the website box at the top of the form, not the regulator URL. Setting a default value here is fine too, but will need to be tested extensively on hide/show of staff and removals/addition.

**Comment by seamuslee001** [comment]
I would argue we probably shouldn't be setting a default value here as we need the regulator form rule to kick in. Perhaps we need a preg match form rule for all of our website fields that validate that there is https://\/http:// in there

**Comment by monishdeb** [comment]
@seamuslee001 @Edzelopez how about adding the url rule for website and staff regulator field like here - https://github.com/JMAConsulting/biz.jmaconsulting.aoservicelisting/pull/39/files#diff-f1b602768726c82b06ab7506c328c897R162 although we also need to add the translation for the error message

**Comment by Edzelopez** [comment]
I'm more inclined towards the formrule method @monishdeb  suggests. How about you @seamuslee001 ?

**Review by Edzelopez — APPROVED** [review]
Changes looks good, merging.

**Pull request merged**
